import Head from "next/head";
import { GetStaticProps } from "next";
import client from "../apollo-client";
import { useBlocks } from "../hooks/useBlocks";
import { Layout } from "../components/Common/Layout";
import { GET_HOME_PAGE } from "../graphql/queries/pages/get-home-page";
import styles from "../styles/Home.module.css";

interface HomeProps {
  data: Blocks;
  menu: string[];
}

interface Blocks {
  title: string;
  blocks: Items;
}

interface Items {
  attributesJSON: string;
  name: string;
  order: number;
}

const Home: React.FC<HomeProps> = ({ data, menu }) => {
  const blocks = useBlocks(data.blocks);

  return (
    <Layout menuItems={menu}>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <h1>{data.title}</h1>
        <main className={styles.main}>{blocks}</main>
      </div>
    </Layout>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const { data } = await client.query({
    query: GET_HOME_PAGE,
  });

  return {
    props: {
      data: data.page,
      menu: data.menuItems.edges,
    },
  };
};

export default Home;
